const X=[
["Richmond", "Mayor", "We Are Richmond", "Dickens Cheung", 0, ""],
["Richmond", "Mayor", "Independent", "Kash Heed", 2, ""],
["Richmond", "Mayor", "Richmond Forward", "Rob Howard", 0, ""],
["Richmond", "Mayor", "Action Richmond", "Mei Kang", 0, ""],
["Richmond", "Mayor", "Independent", "Goldentiger King", 0, ""],
["Richmond", "Mayor", "Independent", "Dennet \"The Cat Guy\" Lee", 0, ""],
["Richmond", "Mayor", "Richmond Strong", "Alexa Loo", 2, ""],
["Richmond", "Mayor", "Independent", "Henry Yao", 0, ""],
["Richmond", "Council", "Independent", "Milan Kuajic", 0, ""],
["Richmond", "Council", "Independent", "Adil Awan", 0, ""],
["Richmond", "Council", "Conservative", "Dale Bains", 0, ""],
["Richmond", "Council", "Richmond Strong", "Bob Basanti", 0, ""],
["Richmond", "Council", "Richmond Forward", "Romeo Bicego", 0, ""],
["Richmond", "Council", "Conservative", "Oday Brahem", 0, ""],
["Richmond", "Council", "We Are Richmond", "Jack Chen", 0, ""],
["Richmond", "Council", "Richmond Citizens' Association", "Alton Cheung", 0, ""],
["Richmond", "Council", "Common Sense Alliance", "Kenny Chiu", 0, ""],
["Richmond", "Council", "Independent", "Mario Cruz", 0, ""],
["Richmond", "Council", "RITE Richmond", "Carol Day", 1, ""],
["Richmond", "Council", "Independent", "Jessy Dhillon", 0, ""],
["Richmond", "Council", "RITE Richmond", "Jerome Dickey", 0, ""],
["Richmond", "Council", "Conservative", "Adam Dobrer", 0, ""],
["Richmond", "Council", "Independent", "Tim Fan", 0, ""],
["Richmond", "Council", "Independent", "Donald Flintoff", 0, ""],
["Richmond", "Council", "Richmond United", "Mike Gill", 0, ""],
["Richmond", "Council", "RITE Richmond", "Laura Gillanders", 1, ""],
["Richmond", "Council", "Action Richmond", "Edward He", 0, ""],
["Richmond", "Council", "Richmond United", "Andy Hobbs", 1, ""],
["Richmond", "Council", "Independent", "Louis Huang", 0, ""],
["Richmond", "Council", "Richmond Forward", "Howard Jampolsky", 0, ""],
["Richmond", "Council", "Richmond Strong", "Jeff Jiang", 0, ""],
["Richmond", "Council", "Independent", "Alan Lackstein", 0, ""],
["Richmond", "Council", "Advance Richmond", "Kevin Lai", 0, ""],
["Richmond", "Council", "ONE Richmond", "Kevin Lainchbury", 0, ""],
["Richmond", "Council", "Advance Richmond", "Gary Law", 0, ""],
["Richmond", "Council", "Independent", "Pak Hing (Ben) Lee", 0, ""],
["Richmond", "Council", "Richmond Forward", "Shelley Leonhardt", 0, ""],
["Richmond", "Council", "Common Sense Alliance", "Thomas Leung", 0, ""],
["Richmond", "Council", "Richmond Citizens' Association", "Vincent Li", 0, ""],
["Richmond", "Council", "We Are Richmond", "Michael Lok", 0, ""],
["Richmond", "Council", "We Are Richmond", "Jenny Mata", 0, ""],
["Richmond", "Council", "Independent", "Andrew Mrozowski", 0, ""],
["Richmond", "Council", "Richmond Strong", "Karen Novorr-Pezzuto", 0, ""],
["Richmond", "Council", "We Are Richmond", "Tony Ortega", 0, ""],
["Richmond", "Council", "Independent", "Dennis Page", 0, ""],
["Richmond", "Council", "Independent", "Hong Yan Melody Pan", 0, ""],
["Richmond", "Council", "Richmond Citizens' Association", "Keefer Pelech", 0, ""],
["Richmond", "Council", "Conservative", "Lisa Phillips", 0, ""],
["Richmond", "Council", "Advance Richmond", "Wallace Pong", 0, ""],
["Richmond", "Council", "Richmond Citizens' Association", "Tamas Revoczi", 0, ""],
["Richmond", "Council", "Conservative", "Alex Sagert", 0, ""],
["Richmond", "Council", "We Are Richmond", "Adnan Sarwar", 0, ""],
["Richmond", "Council", "Advance Richmond", "Sheldon Starrett", 0, ""],
["Richmond", "Council", "Common Sense Alliance", "Glenda Strang", 0, ""],
["Richmond", "Council", "Independent", "Daniel Tsang", 0, ""],
["Richmond", "Council", "Advance Richmond", "Grace Tsang", 0, ""],
["Richmond", "Council", "Independent", "Andy Wang", 0, ""],
["Richmond", "Council", "Advance Richmond", "Sam Wang", 0, ""],
["Richmond", "Council", "Advance Richmond", "William Wang", 0, ""],
["Richmond", "Council", "RITE Richmond", "Michael Wolfe", 1, ""],
["Richmond", "Council", "Richmond Citizens' Association", "Milly Yee", 0, ""],
["Richmond", "Council", "Richmond Forward", "Eric Yung", 0, ""],
["Richmond", "Council", "Richmond Forward", "Melissa Zhang", 0, ""],
["Delta", "Mayor", "Delta First", "Melissa Granum", 0, ""],
["Delta", "Mayor", "Achieving for Delta", "George V. Harvie", 1, ""],
["Delta", "Mayor", "One Delta", "Dylan Kruger", 2, ""],
["Delta", "Council", "Independent", "Wendy Beck-Orlando", 0, ""],
["Delta", "Council", "One Delta", "Rod Binder", 1, ""],
["Delta", "Council", "One Delta", "Sylvia Bishop", 0, ""],
["Delta", "Council", "One Delta", "Daniel Boisvert", 1, ""],
["Delta", "Council", "Achieving for Delta", "Jennyfer Cassar", 0, ""],
["Delta", "Council", "Achieving for Delta", "Jessie Dosanjh", 1, ""],
["Delta", "Council", "Independent", "Ronn Dunnett", 0, ""],
["Delta", "Council", "Delta First", "Alexander Fischer", 0, ""],
["Delta", "Council", "One Delta", "Sarah Gallop", 0, ""],
["Delta", "Council", "Achieving for Delta", "Alicia Guichon", 1, ""],
["Delta", "Council", "Delta First", "Tammy Hansen", 0, ""],
["Delta", "Council", "One Delta", "Jennifer Johal", 1, ""],
["Delta", "Council", "One Delta", "Pawan Joshi", 0, ""],
["Delta", "Council", "Achieving for Delta", "Nick Kanakos", 0, ""],
["Delta", "Council", "Independent", "Gillian McLeod", 0, ""],
["Delta", "Council", "Delta First", "Jat Puri", 0, ""],
["Delta", "Council", "Achieving for Delta", "Ikjot Sandhu-Sahota", 0, ""],
["Delta", "Council", "Achieving for Delta", "Sonya Sangster", 0, ""],
["Delta", "Council", "Independent", "Ron Wasik", 0, ""],
["Delta", "Council", "Independent", "Brian White", 0, ""],
["City of North Vancouver", "Mayor", "Independent", "Linda Buchanan", 1, ""],
["City of North Vancouver", "Mayor", "Independent", "Oliver King", 0, ""],
["City of North Vancouver", "Mayor", "Independent", "Dave Kurvers", 0, ""],
["City of North Vancouver", "Mayor", "Independent", "Mike McGraw", 0, ""],
["City of North Vancouver", "Council", "Independent", "Sean Alexander", 0, ""],
["City of North Vancouver", "Council", "Independent", "Holly Back", 1, ""],
["City of North Vancouver", "Council", "Independent", "Don Bell", 1, ""],
["City of North Vancouver", "Council", "Independent", "Tammy Bentz", 0, ""],
["City of North Vancouver", "Council", "Independent", "Anna Boltenko", 0, ""],
["City of North Vancouver", "Council", "Independent", "David Brun", 0, ""],
["City of North Vancouver", "Council", "Independent", "Jeremy Cato", 0, ""],
["City of North Vancouver", "Council", "Independent", "Angela Girard", 1, ""],
["City of North Vancouver", "Council", "Independent", "Guy Heywood", 0, ""],
["City of North Vancouver", "Council", "Independent", "Ken Izatt", 0, ""],
["City of North Vancouver", "Council", "Independent", "Jullian Kolstee", 0, ""],
["City of North Vancouver", "Council", "Independent", "Max Lai", 0, ""],
["City of North Vancouver", "Council", "Independent", "Jessica McIlroy", 1, ""],
["City of North Vancouver", "Council", "Independent", "Krishna Raisinghani", 0, ""],
["City of North Vancouver", "Council", "Independent", "Andrew Robertson", 0, ""],
["City of North Vancouver", "Council", "Independent", "Shervin Shahriari", 1, ""],
["City of North Vancouver", "Council", "Independent", "Lailani Tumaneng", 0, ""],
["City of North Vancouver", "Council", "Independent", "Tony Valente", 1, ""],
["District of North Vancouver", "Mayor", "Independent", "Graham Alexander", 0, ""],
["District of North Vancouver", "Mayor", "Independent", "Mike Little", 1, ""],
["District of North Vancouver", "Mayor", "Independent", "Stephan Nieweler", 0, ""],
["District of North Vancouver", "Mayor", "Independent", "Paolo Pucci", 0, ""],
["District of North Vancouver", "Mayor", "Independent", "Max Zahedi", 0, ""],
["District of North Vancouver", "Council", "Independent", "Daniel Anderson", 0, ""],
["District of North Vancouver", "Council", "Independent", "Jordan Back", 1, ""],
["District of North Vancouver", "Council", "Independent", "Trey Bell", 0, ""],
["District of North Vancouver", "Council", "Independent", "Mathew Bond", 0, ""],
["District of North Vancouver", "Council", "Independent", "Daina Boyd", 0, ""],
["District of North Vancouver", "Council", "Independent", "Betty Forbes", 1, ""],
["District of North Vancouver", "Council", "Independent", "Jim Hanson", 1, ""],
["District of North Vancouver", "Council", "Independent", "Aidan Kyle", 0, ""],
["District of North Vancouver", "Council", "Independent", "Herman Mah", 1, ""],
["District of North Vancouver", "Council", "Independent", "Kulvir Mann", 0, ""],
["District of North Vancouver", "Council", "Independent", "Linda Munro", 0, ""],
["District of North Vancouver", "Council", "Independent", "Lisa Muri", 1, ""],
["District of North Vancouver", "Council", "Independent", "Victoria Nwabuisi", 0, ""],
["District of North Vancouver", "Council", "Independent", "Catherine Pope", 1, ""],
["District of North Vancouver", "Council", "Independent", "Stephanie Wilson", 0, ""],
["Victoria", "Mayor", "Independent", "Marianne Alto", 1, ""],
["Victoria", "Mayor", "Independent", "Lyall Atkinson", 0, ""],
["Victoria", "Mayor", "Independent", "Darren Gervais-Harrison", 0, ""],
["Victoria", "Mayor", "Independent", "Christopher Hanna", 0, ""],
["Victoria", "Mayor", "Independent", "Mike Harris", 0, ""],
["Victoria", "Mayor", "Independent", "David Johnston", 0, ""],
["Victoria", "Mayor", "Independent", "Bruce McGuigan", 0, ""],
["Victoria", "Mayor", "Independent", "Gregoor Miller", 0, ""],
["Victoria", "Council", "Independent", "Wendy Bowkett", 0, ""],
["Victoria", "Council", "Independent", "Jeremy Caradonna", 1, ""],
["Victoria", "Council", "Independent", "Herb Collins", 0, ""],
["Victoria", "Council", "Independent", "Melissa Cseszko", 0, ""],
["Victoria", "Council", "Independent", "Matt Dell", 1, ""],
["Victoria", "Council", "Independent", "Shona Dion", 0, ""],
["Victoria", "Council", "Independent", "Steve Filipovic", 0, ""],
["Victoria", "Council", "Independent", "Jerry Garcia", 0, ""],
["Victoria", "Council", "Independent", "Marg Gardiner", 1, ""],
["Victoria", "Council", "Victoria For All", "Peter Gibbs", 0, ""],
["Victoria", "Council", "Independent", "Martin Girard", 0, ""],
["Victoria", "Council", "Independent", "Stephen Hammond", 1, ""],
["Victoria", "Council", "Independent", "James Harasymow", 0, ""],
["Victoria", "Council", "Independent", "Jason Heit", 0, ""],
["Victoria", "Council", "Victoria For All", "Susan Kim", 1, ""],
["Victoria", "Council", "Independent", "Bella Lee", 0, ""],
["Victoria", "Council", "Independent", "Krista Loughton", 1, ""],
["Victoria", "Council", "Independent", "Arthur McInnis", 0, ""],
["Victoria", "Council", "Independent", "Karen Rothe", 0, ""],
["Victoria", "Council", "Independent", "Jack Sandor", 0, ""],
["Victoria", "Council", "Independent", "Dave Thompson", 1, ""],
["Nanaimo", "Mayor", "Independent", "Brunie Brunie", 0, ""],
["Nanaimo", "Mayor", "REAL Nanaimo", "Anne-Marie Dryden", 0, ""],
["Nanaimo", "Mayor", "Independent", "Leonard Krog", 1, ""],
["Nanaimo", "Mayor", "Independent", "Sarah Lovegrove", 0, ""],
["Nanaimo", "Council", "REAL Nanaimo", "Jeff Annesley", 0, ""],
["Nanaimo", "Council", "Independent", "Sheryl Armstrong", 1, ""],
["Nanaimo", "Council", "REAL Nanaimo", "Sandy Bartlett", 0, ""],
["Nanaimo", "Council", "Independent", "Kenneth Bennett", 0, ""],
["Nanaimo", "Council", "Independent", "Marnie Boers", 0, ""],
["Nanaimo", "Council", "Independent", "Jackie Bolen", 0, ""],
["Nanaimo", "Council", "Independent", "Mark Chandler", 0, ""],
["Nanaimo", "Council", "Independent", "Paul Chapman", 0, ""],
["Nanaimo", "Council", "REAL Nanaimo", "Malcolm Cooke", 0, ""],
["Nanaimo", "Council", "Independent", "Andréa Coutu", 0, ""],
["Nanaimo", "Council", "Independent", "Shane Crawley", 0, ""],
["Nanaimo", "Council", "Independent", "Ryan Djakovic", 0, ""],
["Nanaimo", "Council", "Independent", "Hilary Eastmure", 1, ""],
["Nanaimo", "Council", "REAL Nanaimo", "Joe Figel", 0, ""],
["Nanaimo", "Council", "Independent", "Meg Fyfe Watkins", 0, ""],
["Nanaimo", "Council", "Independent", "Ben Geselbracht", 1, ""],
["Nanaimo", "Council", "REAL Nanaimo", "Bryan Gordon", 0, ""],
["Nanaimo", "Council", "Independent", "Anita Greer", 0, ""],
["Nanaimo", "Council", "Independent", "Patrick Gunville", 0, ""],
["Nanaimo", "Council", "REAL Nanaimo", "Derek Hanna", 0, ""],
["Nanaimo", "Council", "Independent", "Richard Harlow", 0, ""],
["Nanaimo", "Council", "Independent", "Erin Hemmens", 1, ""],
["Nanaimo", "Council", "Independent", "Steven Johns", 0, ""],
["Nanaimo", "Council", "Independent", "Cameron Leckenby", 0, ""],
["Nanaimo", "Council", "Independent", "Max MacKay", 0, ""],
["Nanaimo", "Council", "Independent", "Paul Manly", 1, ""],
["Nanaimo", "Council", "Independent", "Bryant Marshall", 0, ""],
["Nanaimo", "Council", "Independent", "Bill McKay", 0, ""],
["Nanaimo", "Council", "Independent", "Andrew Merilees", 0, ""],
["Nanaimo", "Council", "Independent", "Matthew Miller", 0, ""],
["Nanaimo", "Council", "Independent", "Zaki Mohammed", 0, ""],
["Nanaimo", "Council", "Independent", "Rod Moreno", 0, ""],
["Nanaimo", "Council", "Independent", "Janice Perrino", 1, ""],
["Nanaimo", "Council", "Independent", "Robert Phelan", 0, ""],
["Nanaimo", "Council", "REAL Nanaimo", "Frank Pluta", 0, ""],
["Nanaimo", "Council", "Independent", "Austin Seng", 0, ""],
["Nanaimo", "Council", "Independent", "Holden Southward", 0, ""],
["Nanaimo", "Council", "Independent", "Ian Thorpe", 1, ""],
["Nanaimo", "Council", "Independent", "Paul Van Ryssel", 0, ""],
["Nanaimo", "Council", "Independent", "Angela Waldick", 0, ""],
];
