// M = MLA candidates: [district, party, name, incumbent, url, bio]. Roles as reported by 27 September 2026.
// The final list from Elections BC (https://elections.bc.ca/2026-provincial-election/candidate-list/, CSV download),
// with party names as Elections BC spells them. Nominations closed 1pm Saturday 3 October. Current to 6 October 2026.
// Vancouver-Strathcona has no incumbent: the seat was vacant at dissolution.
const M=[
["Vancouver-Fraserview","BC Green Party","Francoise Raunet",0,""],
["Vancouver-Fraserview","Conservative Party","Deep Sandhu",0,""],
["Vancouver-Fraserview","BC NDP","Aman Singh",0,"","MLA for Richmond-Queensborough from 2020 to 2024. BC NDP president since November 2025."],
["Vancouver-Hastings","CentreBC","Christian Bosio",0,""],
["Vancouver-Hastings","Communist Party of BC","Kimball Cariou",0,"","Former Communist Party of BC leader. Edited People's Voice for more than 25 years."],
["Vancouver-Hastings","BC Green Party","Kyra Philbert",0,""],
["Vancouver-Hastings","BC NDP","Niki Sharma",1,"","Attorney General and Deputy Premier."],
["Vancouver-Hastings","Conservative Party","Phyllis Tang",0,""],
["Vancouver-Hastings","Libertarian","Phil Webb",0,""],
["Vancouver-Kensington","BC NDP","Mable Elmore",1,"","Deputy Speaker."],
["Vancouver-Kensington","BC Green Party","Adam Hawk",0,""],
["Vancouver-Kensington","Conservative Party","Aron Lageri",0,""],
["Vancouver-Langara","BC Green Party","John Atoyebi",0,""],
["Vancouver-Langara","CentreBC","Alan Beesley",0,""],
["Vancouver-Langara","BC NDP","Sunita Dhir",1,"","Parliamentary Secretary for International Credentials."],
["Vancouver-Langara","Conservative Party","Jaime Stein",0,""],
["Vancouver-Little Mountain","BC NDP","Christine Boyle",1,"","Minister of Housing and Municipal Affairs."],
["Vancouver-Little Mountain","BC Green Party","Sarah MacLeod",0,""],
["Vancouver-Little Mountain","Conservative Party","Alex Muir",0,""],
["Vancouver-Point Grey","CentreBC","Michael Davis",0,""],
["Vancouver-Point Grey","BC NDP","David Eby",1,"","Premier."],
["Vancouver-Point Grey","Conservative Party","Alex McMillan",0,"","Interim CEO of the BC Chamber of Commerce from June 2025 to February 2026."],
["Vancouver-Point Grey","BC Green Party","Beatrice Sharpe",0,""],
["Vancouver-Quilchena","Conservative Party","Carson Binda",0,"","Former BC director of the Canadian Taxpayers Federation."],
["Vancouver-Quilchena","OneBC","Dallas Brodie",1,"","OneBC interim leader. Elected as a Conservative in 2024."],
["Vancouver-Quilchena","BC Green Party","Douglas Courtemanche",0,""],
["Vancouver-Quilchena","CentreBC","Petra Kuret",0,""],
["Vancouver-Quilchena","BC NDP","Callista Ryan",0,""],
["Vancouver-Renfrew","BC NDP","Adrian Dix",1,"","Minister of Energy and Climate Solutions."],
["Vancouver-Renfrew","BC Green Party","Rebecca Haber",0,""],
["Vancouver-Renfrew","Conservative Party","Tom Ikonomou",0,""],
["Vancouver-Renfrew","CentreBC","Lisa Prescott",0,""],
["Vancouver-South Granville","BC Green Party","Maria J Cruz",0,""],
["Vancouver-South Granville","BC NDP","Lara Honrado",0,""],
["Vancouver-South Granville","Conservative Party","Lisa Phillips",0,""],
["Vancouver-South Granville","CentreBC","Colin Smith",0,""],
["Vancouver-South Granville","OneBC","Salvatore Vetro",0,""],
["Vancouver-Strathcona","BC NDP","Amanda Burrows",0,"","Executive director of First United in Vancouver's Downtown Eastside."],
["Vancouver-Strathcona","Communist Party of BC","Robert Crooks",0,"","Communist Party of BC leader since July 2025."],
["Vancouver-Strathcona","Conservative Party","Jordan Zheng McIntosh",0,""],
["Vancouver-Strathcona","BC Green Party","Tanya Webking",0,""],
["Vancouver-West End","BC NDP","Spencer Chandra Herbert",1,"","Minister of Indigenous Relations and Reconciliation."],
["Vancouver-West End","BC Green Party","Scott MacDonald",0,""],
["Vancouver-West End","Conservative Party","Dion Weisner",0,""],
["Vancouver-Yaletown","CentreBC","Sam Chandola",0,"","Conservative Party candidate in North Vancouver-Seymour in 2024."],
["Vancouver-Yaletown","Conservative Party","Margareta Dovgal",0,"","Managing director of Resource Works, a natural resource policy non-profit."],
["Vancouver-Yaletown","BC Green Party","Priyan Samarakoone",0,""],
["Vancouver-Yaletown","Unaffiliated","Timothy Webster",0,""],
["Vancouver-Yaletown","BC NDP","Terry Yung",1,"","Minister of State for Community Safety and Integrated Services."],
["Richmond-Bridgeport","BC NDP","Linda Li",0,""],
["Richmond-Bridgeport","Conservative Party","Teresa Wat",1,"","Elected as a Conservative in 2024, sat as an independent and then with CentreBC from August 2026, and rejoined the Conservative caucus on 22 September."],
["Richmond Centre","CWP","Lawrence Chen",0,"","Also running for Richmond school trustee on 17 October."],
["Richmond Centre","BC Green Party","Calvin Dang",0,""],
["Richmond Centre","Conservative Party","Sacha Peter",0,"","Former chair of the Cultus Lake Park Board, an elected body."],
["Richmond Centre","BC NDP","Henry Yao",0,"","MLA for Richmond South Centre from 2020 to 2024."],
["Richmond-Queensborough","BC Green Party","Luc Burns",0,""],
["Richmond-Queensborough","BC NDP","Dhar Grewal",0,""],
["Richmond-Queensborough","Conservative Party","Steve Kooner",1,"","Opposition critic for Attorney General."],
["Richmond-Steveston","Independent","Robert Evans",0,""],
["Richmond-Steveston","BC NDP","Bruce Kong",0,""],
["Richmond-Steveston","CentreBC","Barry Wosk",0,""],
["Richmond-Steveston","CWP","Keenan Yang",0,""],
["Richmond-Steveston","Conservative Party","Gordon Zhang",0,""],
["Delta North","Conservative Party","Monica Mohan",0,""],
["Delta North","CentreBC","Kuldeep Rangi",0,""],
["Delta North","BC NDP","Todd Schierling",0,"","President of the BC Professional Fire Fighters' Association."],
["Delta South","BC Green Party","Skadi Green",0,""],
["Delta South","BC NDP","Jason McCormick",0,""],
["Delta South","OneBC","Jim McMurtry",0,""],
["Delta South","Conservative Party","Ian Paton",1,"","Elected as a Conservative in 2024, sat as an independent and then with CentreBC from August 2026, and rejoined the Conservative caucus on 22 September."],
["North Vancouver-Lonsdale","BC Green Party","Joshua A Singer Johnson",0,""],
["North Vancouver-Lonsdale","BC NDP","Bowinn Ma",1,"","Minister of Infrastructure."],
["North Vancouver-Lonsdale","Conservative Party","Trevor Withers",0,""],
["North Vancouver-Seymour","Conservative Party","Lynne Block",0,"","MLA for West Vancouver-Capilano until dissolution, and Opposition critic for Education. Running here instead."],
["North Vancouver-Seymour","BC NDP","Susie Chant",1,"","Parliamentary Secretary for Seniors' Services and Long-Term Care."],
["North Vancouver-Seymour","CentreBC","Lori Climenhaga",0,""],
["North Vancouver-Seymour","BC Green Party","Ben Holt",0,""],
["North Vancouver-Seymour","OneBC","Frederick Thiele",0,""],
["West Vancouver-Capilano","BC NDP","Honieh Barzegari",0,""],
["West Vancouver-Capilano","OneBC","Naomi Chocyk",0,""],
["West Vancouver-Capilano","Conservative Party","Caroline Elliott",0,"","Placed second in the 2026 Conservative Party leadership race, which Kerry-Lynne Findlay won."],
["West Vancouver-Capilano","BC Green Party","Arwa Shurab",0,""],
["Victoria-Beacon Hill","Conservative Party","Joachim Agou",0,""],
["Victoria-Beacon Hill","BC NDP","Grace Lore",1,"","Minister without Portfolio."],
["Victoria-Beacon Hill","BC Green Party","Rajinder S. Sahota",0,""],
["Victoria-Swan Lake","BC Green Party","Carolyn Howe",0,"","President of the Greater Victoria Teachers' Association."],
["Victoria-Swan Lake","BC NDP","Nina Krieger",1,"","Minister of Public Safety and Solicitor General."],
["Victoria-Swan Lake","Conservative Party","Tim Taylor",0,""],
["Oak Bay-Gordon Head","BC Green Party","Andrew Appleton",0,"","Oak Bay councillor since 2018."],
["Oak Bay-Gordon Head","BC NDP","Diana Gibson",1,"","Minister of Citizens' Services."],
["Oak Bay-Gordon Head","Conservative Party","Stan Sipos",0,""],
["Oak Bay-Gordon Head","CentreBC","Andrew Weaver",0,"","BC Green Party leader from 2015 to 2020. MLA for Oak Bay-Gordon Head until 2020."],
["Nanaimo-Gabriola Island","Conservative Party","Mark MacDonald",0,"","Publisher of the Business Examiner. Former managing editor of the Nanaimo Daily News."],
["Nanaimo-Gabriola Island","BC NDP","Sheila Malcolmson",1,"","Minister of Social Development and Poverty Reduction."],
["Nanaimo-Gabriola Island","BC Green Party","Anna Mary McKenzie",0,""],
["Nanaimo-Lantzville","BC NDP","George Anderson",1,"","Parliamentary Secretary for Energy and Climate Solutions."],
["Nanaimo-Lantzville","Conservative Party","Kelsey Pringle",0,""],
["Nanaimo-Lantzville","Communist Party of BC","Pepper Saltman",0,""],
["Nanaimo-Lantzville","BC Green Party","Sharleen Weatherley",0,""],
];
