const S=[
["Vancouver", "School", "Vancouver Liberals", "Darren Boidman", 0, "https://www.vancouverliberals.com/darren_boidman"],
["Vancouver", "School", "OneCity", "Sherry Breshears", 0, "https://www.onecityvancouver.ca/our_candidates"],
["Vancouver", "School", "OneCity", "Rory Brown", 0, "https://www.onecityvancouver.ca/people/rory-brown"],
["Vancouver", "School", "Vancouver Liberals", "Joshua Cameron", 0, "https://www.vancouverliberals.com/joshua_cameron"],
["Vancouver", "School", "OneCity", "Steve Cardwell", 0, "https://onecityvancouver.ca/people/steve-cardwell"],
["Vancouver", "School", "COPE", "Melanie Cheng", 0, "https://melaniecheng.ca/"],
["Vancouver", "School", "ABC Vancouver", "Alfred Chien 錢育廷", 0, ""],
["Vancouver", "School", "TrueBlue Vancouver", "Naomi Chocyk", 0, "https://naomichocyk.com/"],
["Vancouver", "School", "TrueBlue Vancouver", "Blair Coleman", 0, ""],
["Vancouver", "School", "Vancouver Liberals", "Ishi Dinim", 0, "https://www.vancouverliberals.com/ishi_dinim"],
["Vancouver", "School", "Vote Vancouver", "Tasha Doucas", 0, ""],
["Vancouver", "School", "ABC Vancouver", "Preeti Faridkot", 0, "https://abcvancouver.ca/"],
["Vancouver", "School", "TrueBlue Vancouver", "Travers Fenton", 0, "http://truebluevancouver.com/"],
["Vancouver", "School", "COPE", "Gwen Giesbrecht", 0, "https://www.votecope.ca/schools"],
["Vancouver", "School", "Vote Vancouver", "Amarys Joseph", 0, ""],
["Vancouver", "School", "ABC Vancouver", "Maria Kritikos", 0, "http://www.kritikosrealestategroup.com/"],
["Vancouver", "School", "ABC Vancouver", "Matt Kroeker", 0, ""],
["Vancouver", "School", "OneCity", "Christopher Lee 李基鵬", 0, "https://www.onecityvancouver.ca/people/christopher-lee"],
["Vancouver", "School", "COPE", "Suzie Mah", 0, "https://www.votecope.ca/schools"],
["Vancouver", "School", "Green", "Alisha Masongsong", 0, "https://www.vangreens.ca/meet_your_candidates"],
["Vancouver", "School", "Vancouver Liberals", "Noosha Mehdian", 0, "https://www.vancouverliberals.com/noosha_mehdian"],
["Vancouver", "School", "ABC Vancouver", "Rob Nijjar", 0, ""],
["Vancouver", "School", "TEAM", "Kat Nystedt", 0, ""],
["Vancouver", "School", "Vancouver Liberals", "Isabel Ochoa Prieto", 0, "https://www.vancouverliberals.com/isabel_ochoa"],
["Vancouver", "School", "COPE", "Derrick O'Keefe", 0, ""],
["Vancouver", "School", "Vote Vancouver", "Mandy Potter", 0, ""],
["Vancouver", "School", "Independent", "Christopher JK Richardson", 0, "https://christopherrichardson.ca/"],
["Vancouver", "School", "OneCity", "Krista Sigurdson", 0, "https://www.onecityvancouver.ca/people/krista-sigurdson"],
["Vancouver", "School", "ABC Vancouver", "Shirley Sio 邵己凌", 0, ""],
["Vancouver", "School", "Green", "Julie Strilesky", 0, ""],
["Vancouver", "School", "ABC Vancouver", "Lina Vargas", 0, ""],
["Richmond", "School", "Advance Richmond", "Dean Billings", 0, ""],
["Richmond", "School", "Advance Richmond", "Rod Belleza", 0, ""],
["Richmond", "School", "Advance Richmond", "Danny Chang", 0, ""],
["Richmond", "School", "Advance Richmond", "Willy Sinconegue", 0, ""],
["Richmond", "School", "Advance Richmond", "Phyllis Tang", 0, ""],
["Richmond", "School", "Advance Richmond", "Sophia Woo", 0, ""],
["Richmond", "School", "Empower", "Debbie Tablotney", 0, ""],
["Richmond", "School", "Empower", "David Yang", 0, ""],
["Richmond", "School", "Empower", "Sandra Nixon", 0, ""],
["Richmond", "School", "Common Sense Alliance", "Alice Wong", 0, ""],
["Richmond", "School", "Richmond Education Party", "Ken Hamaguchi", 0, ""],
["Richmond", "School", "Richmond Education Party", "Heather Larson", 0, ""],
["Richmond", "School", "Richmond Education Party", "Martin Li", 0, ""],
["Richmond", "School", "Richmond Education Party", "Bill Mok", 0, ""],
["Richmond", "School", "Independent", "Hongyun Chen", 0, ""],
["Richmond", "School", "Independent", "Lawrence Chen", 0, ""],
["Richmond", "School", "Independent", "Calvin Dang", 0, ""],
["Richmond", "School", "Independent", "Kiana Dashtbazi", 0, ""],
["Richmond", "School", "Independent", "Kay Hale", 0, ""],
["Richmond", "School", "Independent", "Aithan Kang", 0, ""],
["Richmond", "School", "Independent", "Ausha Kang", 0, ""],
["Richmond", "School", "Independent", "Vivien Lee", 0, ""],
["Richmond", "School", "Independent", "Stefan Mladenovic", 0, ""],
["Richmond", "School", "Independent", "Jordan Oye", 0, ""],
["Richmond", "School", "Independent", "Helen Quan", 0, ""],
["Richmond", "School", "Independent", "Donna Sargent", 0, ""],
["Richmond", "School", "Independent", "Nancy Williams", 0, ""],
["Richmond", "School", "Independent", "John Zhang", 0, ""],
["Delta", "School", "Achieving for Delta", "Erica Beard", 0, ""],
["Delta", "School", "Achieving for Delta", "Nimmi Daula", 0, ""],
["Delta", "School", "Achieving for Delta", "Joe Muego", 0, ""],
["Delta", "School", "Achieving for Delta", "Rick Ocean", 0, ""],
["Delta", "School", "Achieving for Delta", "Nenah Sandy", 0, ""],
["Delta", "School", "Achieving for Delta", "Sagar Sanghera", 0, ""],
["Delta", "School", "Achieving for Delta", "Umendra Singh", 0, ""],
["Delta", "School", "One Delta", "Jesse Bierman", 0, ""],
["Delta", "School", "One Delta", "Tamara Bissett-Laza", 0, ""],
["Delta", "School", "One Delta", "Ammen Dhillon", 0, ""],
["Delta", "School", "One Delta", "Masako Gooch", 0, ""],
["Delta", "School", "One Delta", "Gurinder Kahlon", 0, ""],
["Delta", "School", "One Delta", "Val Windsor", 0, ""],
["Delta", "School", "One Delta", "Amar Hundal", 0, ""],
["Delta", "School", "Independent", "Krissy Eiben", 0, ""],
["Delta", "School", "Independent", "Marcin Huniewicz", 0, ""],
["Delta", "School", "Independent", "Jim Mcmurtry", 0, ""],
["Delta", "School", "Independent", "Rowan St. Germain", 0, ""],
["Nanaimo", "School", "Independent", "Tania Brzovic", 0, ""],
["Nanaimo", "School", "Independent", "Kailey Gillam", 0, ""],
["Nanaimo", "School", "Independent", "Zeni Maartman", 0, ""],
["Nanaimo", "School", "Independent", "Chantelle Morvay", 0, ""],
["Nanaimo", "School", "Independent", "Mark Allan Robinson", 0, ""],
["Nanaimo", "School", "Independent", "Adrianne Cafariello", 0, ""],
["Nanaimo", "School", "Independent", "Tim Harris", 0, ""],
["Nanaimo", "School", "Independent", "Leana Pellegrin", 0, ""],
["Nanaimo", "School", "Independent", "Fred MacDonald", 0, ""],
["Nanaimo", "School", "Independent", "Tom Rokeby", 0, ""],
["Nanaimo", "School", "Independent", "Leanne Lee", 0, ""],
["Victoria", "School", "Victoria For All", "Maiya Beech", 0, ""],
["Victoria", "School", "Independent", "James Le", 0, ""],
["Victoria", "School", "Independent", "Tanner May-Poole", 0, ""],
["Victoria", "School", "Independent", "Angela Carmichael", 0, ""],
["Victoria", "School", "Independent", "Evan Llewellyn", 0, ""],
["Victoria", "School", "Independent", "James McAllister", 0, ""],
["Victoria", "School", "Independent", "Ken Waldron", 0, ""],
["Victoria", "School", "Independent", "Ann Whiteaker", 0, ""],
["District of North Vancouver", "School", "Independent", "Cyndi Gerlach", 0, ""],
["District of North Vancouver", "School", "Independent", "Rob Haines", 0, ""],
["District of North Vancouver", "School", "Independent", "Mike Boehm", 0, ""],
["District of North Vancouver", "School", "Independent", "Jennifer Branston", 0, ""],
["District of North Vancouver", "School", "Independent", "Michael Charrois", 0, ""],
["District of North Vancouver", "School", "Independent", "Barry Forward", 0, ""],
["District of North Vancouver", "School", "Independent", "Emma Juniper", 0, ""],
["District of North Vancouver", "School", "Independent", "Raheela Khan", 0, ""],
["District of North Vancouver", "School", "Independent", "Laura Nickerson", 0, ""],
["District of North Vancouver", "School", "Independent", "Layne North", 0, ""],
["District of North Vancouver", "School", "Independent", "Raphael Perfecto", 0, ""],
["District of North Vancouver", "School", "Independent", "Ainslie Rinfret", 0, ""],
["District of North Vancouver", "School", "Independent", "George Tsiakos", 0, ""],
["City of North Vancouver", "School", "Independent", "Manoochehr Azizi", 0, ""],
["City of North Vancouver", "School", "Independent", "Peggy Hung", 0, ""],
["City of North Vancouver", "School", "Independent", "Senora Navales", 0, ""],
["City of North Vancouver", "School", "Independent", "Trish Neufeld", 0, ""],
["City of North Vancouver", "School", "Independent", "Ethel Purugganan", 0, ""],
["City of North Vancouver", "School", "Independent", "Antje Wilson", 0, ""],
];
